# Generated by Django 5.0.2 on 2024-03-09 19:43

import django.core.validators
import website.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_websitemenu_background_alter_websitemenu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemenu',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to=website.models.document_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'png', 'svg', 'gif', 'jpeg', 'jfif', 'pjpeg', 'pjp'])], verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=website.models.document_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='file'),
        ),
    ]
