# Generated by Django 5.0.2 on 2024-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_slogan_albanian_sponsor_slogan_al_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemenu',
            name='sub_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='websitemenu',
            name='sub_title_al',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='sub title albanian'),
        ),
    ]
