# Generated by Django 5.0.2 on 2024-03-09 21:20

import django.core.validators
import website.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websitemenu_title_websitemenu_title_al'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemenu',
            name='button',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='button'),
        ),
        migrations.AddField(
            model_name='websitemenu',
            name='button_al',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='button albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='background',
            field=models.FileField(blank=True, help_text='Size 1900x1200', null=True, upload_to=website.models.document_file_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv', 'jpg', 'png', 'svg', 'gif', 'jpeg', 'jfif', 'pjpeg', 'pjp'])], verbose_name='background'),
        ),
    ]
