# Generated by Django 5.0.2 on 2024-03-09 21:59

import website.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_websitemenu_button_websitemenu_button_al_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='logo',
            field=models.ImageField(help_text='Size 165x40', null=True, upload_to=website.models.document_file_directory_path, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='menu_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, verbose_name='menu type'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='menu_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, verbose_name='menu type'),
        ),
    ]
