# Generated by Django 5.0.2 on 2024-03-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_websiteinformation_logo_alter_websitemenu_menu_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='subscribe_button',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='subscribe button'),
        ),
        migrations.AddField(
            model_name='websiteinformation',
            name='subscribe_button_al',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='subscribe button albanian'),
        ),
    ]
