# Generated by Django 5.0.2 on 2024-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_websiteinformation_subscribe_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('name_al', models.CharField(max_length=128, verbose_name='name albanian')),
                ('menu_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, verbose_name='menu type')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'menu',
            },
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='name_al',
            field=models.CharField(max_length=128, verbose_name='name albanian'),
        ),
    ]
