# Generated by Django 5.0.2 on 2024-03-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_menu_alter_websitemenu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, unique=True, verbose_name='menu type'),
        ),
    ]
