# Generated by Django 5.0.2 on 2024-03-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_menu_menu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemenu',
            name='date_range',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='date range'),
        ),
        migrations.AddField(
            model_name='websitemenu',
            name='date_range_al',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='date range albanian'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, unique=True, verbose_name='menu type'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, unique=True, verbose_name='menu type'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor')], max_length=30, verbose_name='menu type'),
        ),
    ]
