# Generated by Django 5.0.2 on 2024-03-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_websitemenu_date_range_websitemenu_date_range_al_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='rights_reserved_al',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='rights reserved albanian'),
        ),
    ]
