# Generated by Django 5.0.2 on 2024-03-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_sponsor_facebook_alter_sponsor_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='background_color',
            field=models.CharField(default='#c0c0c0', max_length=7, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='menu',
            name='color',
            field=models.CharField(default='#c0c0c0', max_length=7, verbose_name='color'),
        ),
    ]
