# Generated by Django 5.0.2 on 2024-03-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_menu_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='staff',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='websitemenumedia',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='order'),
        ),
    ]
