# Generated by Django 5.0.2 on 2024-04-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_menu_order_sponsor_order_staff_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='secondary color'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('programme', 'Programme'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor'), ('language', 'Language')], max_length=30, unique=True, verbose_name='menu type'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('programme', 'Programme'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor'), ('language', 'Language')], max_length=30, unique=True, verbose_name='menu type'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='menu_type',
            field=models.CharField(choices=[('index', 'Home'), ('about', 'About'), ('programme', 'Programme'), ('news', 'News'), ('talks_masterclass', 'Talks and Masterclass'), ('schedule', 'Schedule'), ('tickets', 'Tickets'), ('location', 'Location'), ('education', 'Education'), ('archive', 'Archive'), ('privacy_policy', 'Privacy Policy'), ('terms_of_use', 'Terms of Use'), ('legal', 'Legal'), ('staff', 'Staff'), ('sponsor', 'Sponsor'), ('language', 'Language')], max_length=30, verbose_name='menu type'),
        ),
    ]
