# Generated by Django 5.0.2 on 2024-04-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_websiteinformation_secondary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=128, verbose_name='day')),
                ('day_al', models.CharField(max_length=128, verbose_name='day albanian')),
                ('date', models.CharField(max_length=128, verbose_name='date')),
                ('date_al', models.CharField(max_length=128, verbose_name='date albanian')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
            ],
            options={
                'verbose_name': 'day date',
                'verbose_name_plural': 'day dates',
                'db_table': 'day_date',
            },
        ),
        migrations.CreateModel(
            name='DayProgrammes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=128, verbose_name='time')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('title_al', models.CharField(max_length=128, verbose_name='title albanian')),
                ('description', models.CharField(max_length=128, verbose_name='date')),
                ('description_al', models.CharField(max_length=128, verbose_name='description albanian')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
                ('day_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_programmes', to='website.daydate', verbose_name='day date')),
            ],
            options={
                'verbose_name': 'day programme',
                'verbose_name_plural': 'day programmes',
                'db_table': 'day_programme',
            },
        ),
    ]
