# Generated by Django 5.0.2 on 2024-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_dayprogrammes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprogrammes',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dayprogrammes',
            name='description_al',
            field=models.TextField(max_length=1000, verbose_name='description albanian'),
        ),
    ]
