# Generated by Django 5.0.2 on 2024-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_dayprogrammes_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='tiktok',
            field=models.URLField(blank=True, db_index=True, null=True, verbose_name='Tiktok'),
        ),
        migrations.AlterField(
            model_name='dayprogrammes',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dayprogrammes',
            name='description_al',
            field=models.TextField(default='', max_length=1000, verbose_name='description albanian'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slogan',
            field=models.CharField(default='', max_length=500, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='slogan_al',
            field=models.CharField(default='', max_length=500, verbose_name='slogan albanian'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description_al',
            field=models.CharField(default='', max_length=1000, verbose_name='description albanian'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slogan',
            field=models.CharField(default='', max_length=500, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slogan_al',
            field=models.CharField(default='', max_length=500, verbose_name='slogan albanian'),
        ),
        migrations.AlterField(
            model_name='websiteinformation',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='websiteinformation',
            name='description_al',
            field=models.CharField(default='', max_length=1000, verbose_name='description albanian'),
        ),
        migrations.AlterField(
            model_name='websiteinformation',
            name='slogan',
            field=models.CharField(default='', max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='websiteinformation',
            name='slogan_al',
            field=models.CharField(default='', max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='description_al',
            field=models.CharField(default='', max_length=1000, verbose_name='description albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='slogan',
            field=models.CharField(default='', max_length=500, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='slogan_al',
            field=models.CharField(default='', max_length=500, verbose_name='slogan albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='sub_title',
            field=models.CharField(default='', max_length=128, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='websitemenu',
            name='sub_title_al',
            field=models.CharField(default='', max_length=128, verbose_name='sub title albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='description',
            field=models.CharField(default='', max_length=1500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='description_al',
            field=models.CharField(default='', max_length=1500, verbose_name='description albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='list_description',
            field=models.CharField(default='', help_text='separate with "next_description"', max_length=1500, verbose_name='list description'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='list_description_al',
            field=models.CharField(default='', help_text='separate with "next_description"', max_length=1500, verbose_name='list description albanian'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='slogan',
            field=models.CharField(default='', max_length=500, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='websitemenumedia',
            name='slogan_al',
            field=models.CharField(default='', max_length=500, verbose_name='slogan albanian'),
        ),
    ]
