# Generated by Django 5.0.2 on 2024-04-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_sponsor_tiktok_alter_dayprogrammes_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('address_al', models.CharField(max_length=200, verbose_name='address albanian')),
                ('embedded_address', models.URLField(blank=True, db_index=True, max_length=500, null=True, verbose_name='embedded address')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='order')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'db_table': 'location',
            },
        ),
    ]
