# Generated by Django 5.0.2 on 2024-04-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinformation',
            name='tiktok',
            field=models.URLField(blank=True, db_index=True, unique=True, verbose_name='Tiktok'),
        ),
    ]
